//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxRequestDto", Namespace="http://schemas.datacontract.org/2004/07/Stp.TaxEngine.Contract")]
    public partial class TaxRequestDto : object
    {
        
        private string CompanyIdField;
        
        private string CustomerNameField;
        
        private string CustomerNumberField;
        
        private string DivisionCodeField;
        
        private string InvoiceDocumentNumberField;
        
        private ServiceReference.TaxRequestLineDto[] OrderLinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionCode
        {
            get
            {
                return this.DivisionCodeField;
            }
            set
            {
                this.DivisionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceDocumentNumber
        {
            get
            {
                return this.InvoiceDocumentNumberField;
            }
            set
            {
                this.InvoiceDocumentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.TaxRequestLineDto[] OrderLines
        {
            get
            {
                return this.OrderLinesField;
            }
            set
            {
                this.OrderLinesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxRequestLineDto", Namespace="http://schemas.datacontract.org/2004/07/Stp.TaxEngine.Contract")]
    public partial class TaxRequestLineDto : object
    {
        
        private string BusinessLocationCodeField;
        
        private bool CreditIndicatorField;
        
        private decimal DiscountAmountField;
        
        private System.DateTime FiscalDateField;
        
        private decimal FreightAmountField;
        
        private System.DateTime InvoiceDateField;
        
        private string ItemDescriptionField;
        
        private string ItemNumberField;
        
        private decimal LineItemAmountField;
        
        private int LineNumberField;
        
        private string MiscellaneousInfoField;
        
        private decimal OverrideTaxAmountCityField;
        
        private decimal OverrideTaxAmountCountryField;
        
        private decimal OverrideTaxAmountCountyField;
        
        private decimal OverrideTaxAmountDistrictField;
        
        private decimal OverrideTaxAmountSecondaryCityField;
        
        private decimal OverrideTaxAmountSecondaryCountyField;
        
        private decimal OverrideTaxAmountSecondaryStateField;
        
        private decimal OverrideTaxAmountStateField;
        
        private string ProductCodeField;
        
        private int QuantityField;
        
        private string ShipFromCityField;
        
        private string ShipFromCountyField;
        
        private string ShipFromGeoCodeField;
        
        private string ShipFromPostalCodeField;
        
        private string ShipFromStateField;
        
        private string ShipToCityField;
        
        private string ShipToCountryField;
        
        private string ShipToCountyField;
        
        private string ShipToGeoCodeField;
        
        private string ShipToPostalCodeField;
        
        private string ShipToStateField;
        
        private string ShipToTerritoryField;
        
        private decimal TaxAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessLocationCode
        {
            get
            {
                return this.BusinessLocationCodeField;
            }
            set
            {
                this.BusinessLocationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreditIndicator
        {
            get
            {
                return this.CreditIndicatorField;
            }
            set
            {
                this.CreditIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountAmount
        {
            get
            {
                return this.DiscountAmountField;
            }
            set
            {
                this.DiscountAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FiscalDate
        {
            get
            {
                return this.FiscalDateField;
            }
            set
            {
                this.FiscalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreightAmount
        {
            get
            {
                return this.FreightAmountField;
            }
            set
            {
                this.FreightAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription
        {
            get
            {
                return this.ItemDescriptionField;
            }
            set
            {
                this.ItemDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber
        {
            get
            {
                return this.ItemNumberField;
            }
            set
            {
                this.ItemNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineItemAmount
        {
            get
            {
                return this.LineItemAmountField;
            }
            set
            {
                this.LineItemAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiscellaneousInfo
        {
            get
            {
                return this.MiscellaneousInfoField;
            }
            set
            {
                this.MiscellaneousInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountCity
        {
            get
            {
                return this.OverrideTaxAmountCityField;
            }
            set
            {
                this.OverrideTaxAmountCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountCountry
        {
            get
            {
                return this.OverrideTaxAmountCountryField;
            }
            set
            {
                this.OverrideTaxAmountCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountCounty
        {
            get
            {
                return this.OverrideTaxAmountCountyField;
            }
            set
            {
                this.OverrideTaxAmountCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountDistrict
        {
            get
            {
                return this.OverrideTaxAmountDistrictField;
            }
            set
            {
                this.OverrideTaxAmountDistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountSecondaryCity
        {
            get
            {
                return this.OverrideTaxAmountSecondaryCityField;
            }
            set
            {
                this.OverrideTaxAmountSecondaryCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountSecondaryCounty
        {
            get
            {
                return this.OverrideTaxAmountSecondaryCountyField;
            }
            set
            {
                this.OverrideTaxAmountSecondaryCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountSecondaryState
        {
            get
            {
                return this.OverrideTaxAmountSecondaryStateField;
            }
            set
            {
                this.OverrideTaxAmountSecondaryStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OverrideTaxAmountState
        {
            get
            {
                return this.OverrideTaxAmountStateField;
            }
            set
            {
                this.OverrideTaxAmountStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipFromCity
        {
            get
            {
                return this.ShipFromCityField;
            }
            set
            {
                this.ShipFromCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipFromCounty
        {
            get
            {
                return this.ShipFromCountyField;
            }
            set
            {
                this.ShipFromCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipFromGeoCode
        {
            get
            {
                return this.ShipFromGeoCodeField;
            }
            set
            {
                this.ShipFromGeoCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipFromPostalCode
        {
            get
            {
                return this.ShipFromPostalCodeField;
            }
            set
            {
                this.ShipFromPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipFromState
        {
            get
            {
                return this.ShipFromStateField;
            }
            set
            {
                this.ShipFromStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCity
        {
            get
            {
                return this.ShipToCityField;
            }
            set
            {
                this.ShipToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCountry
        {
            get
            {
                return this.ShipToCountryField;
            }
            set
            {
                this.ShipToCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCounty
        {
            get
            {
                return this.ShipToCountyField;
            }
            set
            {
                this.ShipToCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToGeoCode
        {
            get
            {
                return this.ShipToGeoCodeField;
            }
            set
            {
                this.ShipToGeoCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToPostalCode
        {
            get
            {
                return this.ShipToPostalCodeField;
            }
            set
            {
                this.ShipToPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToState
        {
            get
            {
                return this.ShipToStateField;
            }
            set
            {
                this.ShipToStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToTerritory
        {
            get
            {
                return this.ShipToTerritoryField;
            }
            set
            {
                this.ShipToTerritoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Stp.TaxEngine.Contract")]
    public partial class TaxResponseDto : object
    {
        
        private int CompletionCodeField;
        
        private string CompletionCodeDescriptionField;
        
        private int NumberOfRecordsField;
        
        private ServiceReference.TaxResponseLineDto[] OrderLinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletionCode
        {
            get
            {
                return this.CompletionCodeField;
            }
            set
            {
                this.CompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompletionCodeDescription
        {
            get
            {
                return this.CompletionCodeDescriptionField;
            }
            set
            {
                this.CompletionCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRecords
        {
            get
            {
                return this.NumberOfRecordsField;
            }
            set
            {
                this.NumberOfRecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.TaxResponseLineDto[] OrderLines
        {
            get
            {
                return this.OrderLinesField;
            }
            set
            {
                this.OrderLinesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxResponseLineDto", Namespace="http://schemas.datacontract.org/2004/07/Stp.TaxEngine.Contract")]
    public partial class TaxResponseLineDto : object
    {
        
        private decimal CalculatedCityTaxAmountField;
        
        private decimal CalculatedCountryTaxAmountField;
        
        private decimal CalculatedCountyTaxAmountField;
        
        private decimal CalculatedDistrictTaxAmountField;
        
        private decimal CalculatedSecondaryCityTaxAmountField;
        
        private decimal CalculatedSecondaryCountyTaxAmountField;
        
        private decimal CalculatedSecondaryStateTaxAmountField;
        
        private decimal CalculatedStateTaxAmountField;
        
        private decimal CalculatedTotalTaxAmountField;
        
        private int CityCompletionCodeField;
        
        private string CityJurisdictionField;
        
        private string CityStpTaxAuthorityCodeField;
        
        private decimal CityTaxRateField;
        
        private string CountryStpTaxAuthorityCodeField;
        
        private decimal CountryTaxRateField;
        
        private string CountyCodeJurisdictionField;
        
        private int CountyCompletionCodeField;
        
        private string CountyJurisdictionField;
        
        private string CountyStpTaxAuthorityCodeField;
        
        private decimal CountyTaxRateField;
        
        private string DistrictStpTaxAuthorityCodeField;
        
        private decimal DistrictTaxRateField;
        
        private int FederalCompletionCodeField;
        
        private int GeneralCompletionCodeField;
        
        private string GeneralCompletionCodeDescriptionField;
        
        private string GeoCodeJurisdictionField;
        
        private string ItemNumberField;
        
        private int LineNumberField;
        
        private int SecondaryCityCompletionCodeField;
        
        private string SecondaryCityStpTaxAuthorityCodeField;
        
        private decimal SecondaryCityTaxRateField;
        
        private int SecondaryCountyCompletionCodeField;
        
        private string SecondaryCountyStpTaxAuthorityCodeField;
        
        private decimal SecondaryCountyTaxRateField;
        
        private int SecondaryStateCompletionCodeField;
        
        private string SecondaryStateStpTaxAuthorityCodeField;
        
        private decimal SecondaryStateTaxRateField;
        
        private int StateCompletionCodeField;
        
        private string StateJurisdictionField;
        
        private string StateStpTaxAuthorityCodeField;
        
        private decimal StateTaxRateField;
        
        private System.DateTime SystemDateField;
        
        private string TaxCertificateCityField;
        
        private string TaxCertificateCountryField;
        
        private string TaxCertificateCountyField;
        
        private string TaxCertificateStateField;
        
        private string ZipCodeJurisdictionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedCityTaxAmount
        {
            get
            {
                return this.CalculatedCityTaxAmountField;
            }
            set
            {
                this.CalculatedCityTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedCountryTaxAmount
        {
            get
            {
                return this.CalculatedCountryTaxAmountField;
            }
            set
            {
                this.CalculatedCountryTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedCountyTaxAmount
        {
            get
            {
                return this.CalculatedCountyTaxAmountField;
            }
            set
            {
                this.CalculatedCountyTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedDistrictTaxAmount
        {
            get
            {
                return this.CalculatedDistrictTaxAmountField;
            }
            set
            {
                this.CalculatedDistrictTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedSecondaryCityTaxAmount
        {
            get
            {
                return this.CalculatedSecondaryCityTaxAmountField;
            }
            set
            {
                this.CalculatedSecondaryCityTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedSecondaryCountyTaxAmount
        {
            get
            {
                return this.CalculatedSecondaryCountyTaxAmountField;
            }
            set
            {
                this.CalculatedSecondaryCountyTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedSecondaryStateTaxAmount
        {
            get
            {
                return this.CalculatedSecondaryStateTaxAmountField;
            }
            set
            {
                this.CalculatedSecondaryStateTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedStateTaxAmount
        {
            get
            {
                return this.CalculatedStateTaxAmountField;
            }
            set
            {
                this.CalculatedStateTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculatedTotalTaxAmount
        {
            get
            {
                return this.CalculatedTotalTaxAmountField;
            }
            set
            {
                this.CalculatedTotalTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityCompletionCode
        {
            get
            {
                return this.CityCompletionCodeField;
            }
            set
            {
                this.CityCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityJurisdiction
        {
            get
            {
                return this.CityJurisdictionField;
            }
            set
            {
                this.CityJurisdictionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityStpTaxAuthorityCode
        {
            get
            {
                return this.CityStpTaxAuthorityCodeField;
            }
            set
            {
                this.CityStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityTaxRate
        {
            get
            {
                return this.CityTaxRateField;
            }
            set
            {
                this.CityTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryStpTaxAuthorityCode
        {
            get
            {
                return this.CountryStpTaxAuthorityCodeField;
            }
            set
            {
                this.CountryStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountryTaxRate
        {
            get
            {
                return this.CountryTaxRateField;
            }
            set
            {
                this.CountryTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountyCodeJurisdiction
        {
            get
            {
                return this.CountyCodeJurisdictionField;
            }
            set
            {
                this.CountyCodeJurisdictionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountyCompletionCode
        {
            get
            {
                return this.CountyCompletionCodeField;
            }
            set
            {
                this.CountyCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountyJurisdiction
        {
            get
            {
                return this.CountyJurisdictionField;
            }
            set
            {
                this.CountyJurisdictionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountyStpTaxAuthorityCode
        {
            get
            {
                return this.CountyStpTaxAuthorityCodeField;
            }
            set
            {
                this.CountyStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyTaxRate
        {
            get
            {
                return this.CountyTaxRateField;
            }
            set
            {
                this.CountyTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictStpTaxAuthorityCode
        {
            get
            {
                return this.DistrictStpTaxAuthorityCodeField;
            }
            set
            {
                this.DistrictStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DistrictTaxRate
        {
            get
            {
                return this.DistrictTaxRateField;
            }
            set
            {
                this.DistrictTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FederalCompletionCode
        {
            get
            {
                return this.FederalCompletionCodeField;
            }
            set
            {
                this.FederalCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GeneralCompletionCode
        {
            get
            {
                return this.GeneralCompletionCodeField;
            }
            set
            {
                this.GeneralCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralCompletionCodeDescription
        {
            get
            {
                return this.GeneralCompletionCodeDescriptionField;
            }
            set
            {
                this.GeneralCompletionCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoCodeJurisdiction
        {
            get
            {
                return this.GeoCodeJurisdictionField;
            }
            set
            {
                this.GeoCodeJurisdictionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber
        {
            get
            {
                return this.ItemNumberField;
            }
            set
            {
                this.ItemNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondaryCityCompletionCode
        {
            get
            {
                return this.SecondaryCityCompletionCodeField;
            }
            set
            {
                this.SecondaryCityCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryCityStpTaxAuthorityCode
        {
            get
            {
                return this.SecondaryCityStpTaxAuthorityCodeField;
            }
            set
            {
                this.SecondaryCityStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SecondaryCityTaxRate
        {
            get
            {
                return this.SecondaryCityTaxRateField;
            }
            set
            {
                this.SecondaryCityTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondaryCountyCompletionCode
        {
            get
            {
                return this.SecondaryCountyCompletionCodeField;
            }
            set
            {
                this.SecondaryCountyCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryCountyStpTaxAuthorityCode
        {
            get
            {
                return this.SecondaryCountyStpTaxAuthorityCodeField;
            }
            set
            {
                this.SecondaryCountyStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SecondaryCountyTaxRate
        {
            get
            {
                return this.SecondaryCountyTaxRateField;
            }
            set
            {
                this.SecondaryCountyTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondaryStateCompletionCode
        {
            get
            {
                return this.SecondaryStateCompletionCodeField;
            }
            set
            {
                this.SecondaryStateCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryStateStpTaxAuthorityCode
        {
            get
            {
                return this.SecondaryStateStpTaxAuthorityCodeField;
            }
            set
            {
                this.SecondaryStateStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SecondaryStateTaxRate
        {
            get
            {
                return this.SecondaryStateTaxRateField;
            }
            set
            {
                this.SecondaryStateTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateCompletionCode
        {
            get
            {
                return this.StateCompletionCodeField;
            }
            set
            {
                this.StateCompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateJurisdiction
        {
            get
            {
                return this.StateJurisdictionField;
            }
            set
            {
                this.StateJurisdictionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateStpTaxAuthorityCode
        {
            get
            {
                return this.StateStpTaxAuthorityCodeField;
            }
            set
            {
                this.StateStpTaxAuthorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateTaxRate
        {
            get
            {
                return this.StateTaxRateField;
            }
            set
            {
                this.StateTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SystemDate
        {
            get
            {
                return this.SystemDateField;
            }
            set
            {
                this.SystemDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxCertificateCity
        {
            get
            {
                return this.TaxCertificateCityField;
            }
            set
            {
                this.TaxCertificateCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxCertificateCountry
        {
            get
            {
                return this.TaxCertificateCountryField;
            }
            set
            {
                this.TaxCertificateCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxCertificateCounty
        {
            get
            {
                return this.TaxCertificateCountyField;
            }
            set
            {
                this.TaxCertificateCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxCertificateState
        {
            get
            {
                return this.TaxCertificateStateField;
            }
            set
            {
                this.TaxCertificateStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCodeJurisdiction
        {
            get
            {
                return this.ZipCodeJurisdictionField;
            }
            set
            {
                this.ZipCodeJurisdictionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITaxService")]
    public interface ITaxService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/CalculateTax", ReplyAction="http://tempuri.org/ITaxService/CalculateTaxResponse")]
        ServiceReference.TaxResponseDto CalculateTax(ServiceReference.TaxRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/CalculateTax", ReplyAction="http://tempuri.org/ITaxService/CalculateTaxResponse")]
        System.Threading.Tasks.Task<ServiceReference.TaxResponseDto> CalculateTaxAsync(ServiceReference.TaxRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/CommitTaxCalculation", ReplyAction="http://tempuri.org/ITaxService/CommitTaxCalculationResponse")]
        ServiceReference.TaxResponseDto CommitTaxCalculation(ServiceReference.TaxRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/CommitTaxCalculation", ReplyAction="http://tempuri.org/ITaxService/CommitTaxCalculationResponse")]
        System.Threading.Tasks.Task<ServiceReference.TaxResponseDto> CommitTaxCalculationAsync(ServiceReference.TaxRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/ReleaseResources", ReplyAction="http://tempuri.org/ITaxService/ReleaseResourcesResponse")]
        void ReleaseResources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/ReleaseResources", ReplyAction="http://tempuri.org/ITaxService/ReleaseResourcesResponse")]
        System.Threading.Tasks.Task ReleaseResourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/RefreshSettings", ReplyAction="http://tempuri.org/ITaxService/RefreshSettingsResponse")]
        void RefreshSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/RefreshSettings", ReplyAction="http://tempuri.org/ITaxService/RefreshSettingsResponse")]
        System.Threading.Tasks.Task RefreshSettingsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    public interface ITaxServiceChannel : ServiceReference.ITaxService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview1.20574.1")]
    public partial class TaxServiceClient : System.ServiceModel.ClientBase<ServiceReference.ITaxService>, ServiceReference.ITaxService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaxServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TaxServiceClient.GetBindingForEndpoint(endpointConfiguration), TaxServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaxServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaxServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference.TaxResponseDto CalculateTax(ServiceReference.TaxRequestDto request)
        {
            return base.Channel.CalculateTax(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TaxResponseDto> CalculateTaxAsync(ServiceReference.TaxRequestDto request)
        {
            return base.Channel.CalculateTaxAsync(request);
        }
        
        public ServiceReference.TaxResponseDto CommitTaxCalculation(ServiceReference.TaxRequestDto request)
        {
            return base.Channel.CommitTaxCalculation(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TaxResponseDto> CommitTaxCalculationAsync(ServiceReference.TaxRequestDto request)
        {
            return base.Channel.CommitTaxCalculationAsync(request);
        }
        
        public void ReleaseResources()
        {
            base.Channel.ReleaseResources();
        }
        
        public System.Threading.Tasks.Task ReleaseResourcesAsync()
        {
            return base.Channel.ReleaseResourcesAsync();
        }
        
        public void RefreshSettings()
        {
            base.Channel.RefreshSettings();
        }
        
        public System.Threading.Tasks.Task RefreshSettingsAsync()
        {
            return base.Channel.RefreshSettingsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ITaxService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ITaxService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ITaxService1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                httpsBindingElement.AuthenticationScheme = System.Net.AuthenticationSchemes.Negotiate;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ITaxService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://stp-devoms217:8000/Stp.TaxEngine/TaxService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ITaxService))
            {
                return new System.ServiceModel.EndpointAddress("http://stp-devoms217:8000/Stp.TaxEngine/TaxService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ITaxService1))
            {
                return new System.ServiceModel.EndpointAddress("https://stp-devoms217:8000/Stp.TaxEngine/TaxService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_ITaxService,
            
            WSHttpBinding_ITaxService,
            
            WSHttpBinding_ITaxService1,
        }
    }
}
